"""empty message

Revision ID: 51c39098991e
Revises: 3108f644ea9c
Create Date: 2018-12-24 16:42:07.948799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c39098991e'
down_revision = '3108f644ea9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('images', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'images')
    # ### end Alembic commands ###
